# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=100)),
                ('Firstname', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Level', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('Phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
